### ISSUE TITLE
[Token API] Create, configure, and test ElasticSearch service

### ISSUE THREAD

**Issue by lucas3003** [HathorNetwork/hathor-explorer-service#137]
### Acceptance Criteria

ElasticSearch cluster must be created and ready to be used, according to the [Token API Design document](https://github.com/HathorNetwork/hathor-explorer-service/issues/123)

**Comment by luislhl** [comment]
We have decided to create the cluster using their offer in AWS Marketplace: https://aws.amazon.com/marketplace/pp/prodview-voru33wi6xs7k?sr=0-2&ref_=beagle&applicationId=AWSMPContessa

This will allow us to have a cluster in Elastic Cloud, but with billing attached to our AWS account.

There is a documentation about this: https://www.elastic.co/guide/en/cloud/current/ec-billing-aws.html

But something worth mentioning, taken from this doc, is this:

> Elastic provides different [subscription levels](https://www.elastic.co/subscriptions/cloud). During your 7-day trial you will automatically have an Enterprise level subscription. After the trial you can choose the subscription level.

Because of this detail, the cost estimation I received when creating the cluster was 2x what we were expecting. But since this is caused by the subscription level, and we will be able to change this subscription level after the trial, then I think costs will normalize once we do this.

Another important thing is that we agreed to create the cluster in eu-central-1, to stay closer to the Lambdas and Logstash, which are all in eu-central-1. This will assure lower latency and lower Data Transfer costs, although the cluster cost will be $17/month higher.
